/**
 * Category → emoji fallback map + name-keyword matching
 */

const categoryEmoji: Record<string, string> = {
  latticini: "🧀", dairy: "🧀",
  carne: "🥩", meat: "🥩",
  frutta: "🍎", fruit: "🍎",
  verdura: "🥬", vegetables: "🥬", vegetable: "🥬",
  bevande: "🥤", drinks: "🥤", drink: "🥤",
  pane: "🍞", bread: "🍞", bakery: "🍞",
  pesce: "🐟", fish: "🐟", seafood: "🐟",
  surgelati: "🧊", frozen: "🧊",
  condimenti: "🫒", condiments: "🫒",
  dolci: "🍫", sweets: "🍫", dessert: "🍰",
  cereali: "🌾", cereals: "🌾", grains: "🌾",
  uova: "🥚", eggs: "🥚",
  pasta: "🍝",
  legumi: "🫘", legumes: "🫘",
  snack: "🍿",
  olio: "🫒", oil: "🫒",
  riso: "🍚", rice: "🍚",
  formaggio: "🧀", cheese: "🧀",
  salumi: "🥓",
  spezie: "🌿", spices: "🌿",
  acqua: "💧", water: "💧",
  vino: "🍷", wine: "🍷",
  birra: "🍺", beer: "🍺",
  caffè: "☕", coffee: "☕",
  tè: "🍵", tea: "🍵",
  succo: "🧃", juice: "🧃",
  latte: "🥛", milk: "🥛",
  yogurt: "🥛",
  burro: "🧈", butter: "🧈",
  miele: "🍯", honey: "🍯",
  pizza: "🍕",
  insalata: "🥗", salad: "🥗",
  zuppa: "🍲", soup: "🍲",
  gelato: "🍦", icecream: "🍦",
  cioccolato: "🍫", chocolate: "🍫",
  biscotti: "🍪", cookies: "🍪", biscuit: "🍪",
  torta: "🎂", cake: "🎂",
  salsa: "🥫", sauce: "🥫",
  conserve: "🥫", canned: "🥫",
};

/** keyword → emoji for matching product names */
const nameKeywords: [string, string][] = [
  // Dolci / snack
  ["caramell", "🍬"],
  ["candy", "🍬"],
  ["lollipop", "🍭"],
  ["barrett", "🍫"],
  ["barretta", "🍫"],
  ["protein bar", "🍫"],
  ["energy bar", "🍫"],
  ["cioccolat", "🍫"],
  ["chocolate", "🍫"],
  ["biscott", "🍪"],
  ["cookie", "🍪"],
  ["wafer", "🍪"],
  ["croissant", "🥐"],
  ["brioche", "🥐"],
  ["cornetto", "🥐"],
  ["muffin", "🧁"],
  ["cupcake", "🧁"],
  ["torta", "🎂"],
  ["cake", "🎂"],
  ["gelato", "🍦"],
  ["ice cream", "🍦"],
  ["patatine", "🍟"],
  ["chips", "🍟"],
  ["popcorn", "🍿"],
  ["cracker", "🍘"],
  ["grissini", "🥖"],
  ["merendina", "🧁"],
  ["snack", "🍿"],
  ["chewing", "🍬"],
  ["gomma", "🍬"],
  ["marmellata", "🍯"],
  ["confettura", "🍯"],
  ["nutella", "🍫"],
  ["crema", "🍫"],

  // Bevande
  ["acqua", "💧"],
  ["water", "💧"],
  ["coca cola", "🥤"],
  ["cola", "🥤"],
  ["fanta", "🥤"],
  ["sprite", "🥤"],
  ["aranciata", "🥤"],
  ["gassosa", "🥤"],
  ["succo", "🧃"],
  ["juice", "🧃"],
  ["latte", "🥛"],
  ["milk", "🥛"],
  ["yogurt", "🥛"],
  ["caffè", "☕"],
  ["coffee", "☕"],
  ["espresso", "☕"],
  ["cappuccino", "☕"],
  ["tè", "🍵"],
  ["tea", "🍵"],
  ["tisana", "🍵"],
  ["vino", "🍷"],
  ["wine", "🍷"],
  ["birra", "🍺"],
  ["beer", "🍺"],
  ["prosecco", "🥂"],
  ["spumante", "🥂"],
  ["champagne", "🥂"],
  ["smoothie", "🥤"],
  ["frullato", "🥤"],
  ["energy drink", "🥤"],

  // Pane / cereali
  ["pane", "🍞"],
  ["bread", "🍞"],
  ["panino", "🥪"],
  ["sandwich", "🥪"],
  ["toast", "🍞"],
  ["fette biscottate", "🍞"],
  ["cereali", "🥣"],
  ["muesli", "🥣"],
  ["granola", "🥣"],
  ["cornflakes", "🥣"],
  ["avena", "🌾"],
  ["oat", "🌾"],
  ["riso", "🍚"],
  ["rice", "🍚"],
  ["pasta", "🍝"],
  ["spaghetti", "🍝"],
  ["penne", "🍝"],
  ["fusilli", "🍝"],
  ["tagliatelle", "🍝"],
  ["lasagna", "🍝"],
  ["gnocchi", "🍝"],
  ["farina", "🌾"],
  ["flour", "🌾"],
  ["pizza", "🍕"],
  ["focaccia", "🍕"],
  ["baguette", "🥖"],
  ["piadina", "🥙"],
  ["wrap", "🥙"],
  ["tortilla", "🌮"],

  // Frutta
  ["mela", "🍎"],
  ["apple", "🍎"],
  ["banana", "🍌"],
  ["arancia", "🍊"],
  ["orange", "🍊"],
  ["mandarino", "🍊"],
  ["limone", "🍋"],
  ["lemon", "🍋"],
  ["fragola", "🍓"],
  ["strawberr", "🍓"],
  ["pesca", "🍑"],
  ["peach", "🍑"],
  ["uva", "🍇"],
  ["grape", "🍇"],
  ["ciliegia", "🍒"],
  ["cherry", "🍒"],
  ["anguria", "🍉"],
  ["watermelon", "🍉"],
  ["melone", "🍈"],
  ["melon", "🍈"],
  ["pera", "🍐"],
  ["pear", "🍐"],
  ["ananas", "🍍"],
  ["pineapple", "🍍"],
  ["cocco", "🥥"],
  ["coconut", "🥥"],
  ["kiwi", "🥝"],
  ["avocado", "🥑"],
  ["mango", "🥭"],
  ["mirtill", "🫐"],
  ["blueberr", "🫐"],
  ["frutta secca", "🥜"],
  ["noci", "🥜"],
  ["walnut", "🥜"],
  ["mandorle", "🥜"],
  ["almond", "🥜"],
  ["nocciole", "🥜"],
  ["hazelnut", "🥜"],
  ["arachidi", "🥜"],
  ["peanut", "🥜"],
  ["pistacchi", "🥜"],

  // Verdura
  ["pomodor", "🍅"],
  ["tomato", "🍅"],
  ["carota", "🥕"],
  ["carrot", "🥕"],
  ["patata", "🥔"],
  ["potato", "🥔"],
  ["insalata", "🥗"],
  ["lattuga", "🥬"],
  ["spinaci", "🥬"],
  ["spinach", "🥬"],
  ["broccol", "🥦"],
  ["zucchina", "🥒"],
  ["cetriolo", "🥒"],
  ["cucumber", "🥒"],
  ["peperone", "🫑"],
  ["pepper", "🫑"],
  ["cipolla", "🧅"],
  ["onion", "🧅"],
  ["aglio", "🧄"],
  ["garlic", "🧄"],
  ["mais", "🌽"],
  ["corn", "🌽"],
  ["fungh", "🍄"],
  ["mushroom", "🍄"],
  ["melanzana", "🍆"],
  ["eggplant", "🍆"],
  ["peperoncin", "🌶️"],
  ["chili", "🌶️"],
  ["zucca", "🎃"],

  // Proteine
  ["pollo", "🍗"],
  ["chicken", "🍗"],
  ["tacchino", "🍗"],
  ["turkey", "🍗"],
  ["manzo", "🥩"],
  ["beef", "🥩"],
  ["maiale", "🥩"],
  ["pork", "🥩"],
  ["salsiccia", "🌭"],
  ["würstel", "🌭"],
  ["hot dog", "🌭"],
  ["hamburger", "🍔"],
  ["burger", "🍔"],
  ["prosciutto", "🥓"],
  ["bacon", "🥓"],
  ["salame", "🥓"],
  ["mortadella", "🥓"],
  ["bresaola", "🥓"],
  ["tonno", "🐟"],
  ["tuna", "🐟"],
  ["salmone", "🐟"],
  ["salmon", "🐟"],
  ["pesce", "🐟"],
  ["fish", "🐟"],
  ["gamber", "🦐"],
  ["shrimp", "🦐"],
  ["uova", "🥚"],
  ["uovo", "🥚"],
  ["egg", "🥚"],
  ["tofu", "🧈"],

  // Latticini
  ["formaggio", "🧀"],
  ["cheese", "🧀"],
  ["mozzarella", "🧀"],
  ["parmigiano", "🧀"],
  ["ricotta", "🧀"],
  ["gorgonzola", "🧀"],
  ["burro", "🧈"],
  ["butter", "🧈"],
  ["panna", "🥛"],
  ["cream", "🥛"],

  // Condimenti / altro
  ["olio", "🫒"],
  ["oil", "🫒"],
  ["aceto", "🫒"],
  ["vinegar", "🫒"],
  ["sale", "🧂"],
  ["salt", "🧂"],
  ["zucchero", "🍬"],
  ["sugar", "🍬"],
  ["ketchup", "🥫"],
  ["maionese", "🥫"],
  ["mayo", "🥫"],
  ["senape", "🥫"],
  ["mustard", "🥫"],
  ["miele", "🍯"],
  ["honey", "🍯"],
  ["salsa", "🥫"],

  // Legumi
  ["fagioli", "🫘"],
  ["beans", "🫘"],
  ["lenticchie", "🫘"],
  ["lentil", "🫘"],
  ["ceci", "🫘"],
  ["chickpea", "🫘"],
  ["piselli", "🫛"],
  ["peas", "🫛"],

  // Piatti pronti
  ["sushi", "🍣"],
  ["taco", "🌮"],
  ["burrito", "🌯"],
  ["curry", "🍛"],
  ["ramen", "🍜"],
  ["zuppa", "🍲"],
  ["soup", "🍲"],
  ["stew", "🍲"],
  ["risotto", "🍚"],
];

export function getFoodEmoji(category: string | null | undefined, name?: string | null): string {
  // 1. Try matching product name keywords first (more specific)
  if (name) {
    const lower = name.toLowerCase().trim();
    for (const [kw, emoji] of nameKeywords) {
      if (lower.includes(kw)) return emoji;
    }
  }

  // 2. Try category
  if (category) {
    const key = category.toLowerCase().trim();
    if (categoryEmoji[key]) return categoryEmoji[key];
  }

  // 3. Generic food fallback
  return "🛒";
}

export function getFoodImage(
  imageUrl: string | null | undefined,
  category: string | null | undefined,
  name?: string | null
): { type: "image" | "emoji"; value: string } {
  if (imageUrl) return { type: "image", value: imageUrl };
  return { type: "emoji", value: getFoodEmoji(category, name) };
}
