/**
 * Category → emoji fallback map + name-keyword matching
 */

const categoryEmoji: Record<string, string> = {
  latticini: "🧀", dairy: "🧀",
  carne: "🥩", meat: "🥩",
  frutta: "🍎", fruit: "🍎",
  verdura: "🥬", vegetables: "🥬", vegetable: "🥬",
  bevande: "🥤", drinks: "🥤", drink: "🥤",
  pane: "🍞", bread: "🍞", bakery: "🍞",
  pesce: "🐟", fish: "🐟", seafood: "🐟",
  surgelati: "🧊", frozen: "🧊",
  condimenti: "🫒", condiments: "🫒",
  dolci: "🍫", sweets: "🍫", dessert: "🍰",
  cereali: "🌾", cereals: "🌾", grains: "🌾",
  uova: "🥚", eggs: "🥚",
  pasta: "🍝",
  legumi: "🫘", legumes: "🫘",
  snack: "🍿",
  olio: "🫒", oil: "🫒",
  riso: "🍚", rice: "🍚",
  formaggio: "🧀", cheese: "🧀",
  salumi: "🥓",
  spezie: "🌿", spices: "🌿",
  acqua: "💧", water: "💧",
  vino: "🍷", wine: "🍷",
  birra: "🍺", beer: "🍺",
  caffè: "☕", coffee: "☕",
  tè: "🍵", tea: "🍵",
  succo: "🧃", juice: "🧃",
  latte: "🥛", milk: "🥛",
  yogurt: "🥛",
  burro: "🧈", butter: "🧈",
  miele: "🍯", honey: "🍯",
  pizza: "🍕",
  insalata: "🥗", salad: "🥗",
  zuppa: "🍲", soup: "🍲",
  gelato: "🍦", icecream: "🍦",
  cioccolato: "🍫", chocolate: "🍫",
  biscotti: "🍪", cookies: "🍪", biscuit: "🍪",
  torta: "🎂", cake: "🎂",
  salsa: "🥫", sauce: "🥫",
  conserve: "🥫", canned: "🥫",
};

/** keyword → emoji for matching product names.
 * Sorted: longer/more-specific stems first so they match before shorter ones.
 */
const nameKeywords: [string, string][] = [
  // ─── Dolci / snack ───
  ["caramell", "🍬"],
  ["candy", "🍬"],
  ["candies", "🍬"],
  ["lollipop", "🍭"],
  ["barrett", "🍫"],
  ["protein bar", "🍫"],
  ["energy bar", "🍫"],
  ["cioccolat", "🍫"],
  ["chocolat", "🍫"],
  ["biscott", "🍪"],
  ["cookie", "🍪"],
  ["wafer", "🍪"],
  ["croissant", "🥐"],
  ["brioche", "🥐"],
  ["cornett", "🥐"],
  ["muffin", "🧁"],
  ["cupcake", "🧁"],
  ["torta", "🎂"],
  ["tortino", "🎂"],
  ["cake", "🎂"],
  ["gelat", "🍦"],
  ["ice cream", "🍦"],
  ["patatine", "🍟"],
  ["chips", "🍟"],
  ["popcorn", "🍿"],
  ["cracker", "🍘"],
  ["grissin", "🥖"],
  ["merendin", "🧁"],
  ["snack", "🍿"],
  ["chewing", "🍬"],
  ["gomm", "🍬"],
  ["marmellat", "🍯"],
  ["confettur", "🍯"],
  ["nutella", "🍫"],
  ["crema nocc", "🍫"],
  ["crema cioc", "🍫"],
  ["crema spalm", "🍫"],

  // ─── Bevande ───
  ["acqua", "💧"],
  ["water", "💧"],
  ["coca cola", "🥤"],
  ["cola", "🥤"],
  ["fanta", "🥤"],
  ["sprite", "🥤"],
  ["aranciat", "🥤"],
  ["gassos", "🥤"],
  ["succ", "🧃"],
  ["latte", "🥛"],
  ["milk", "🥛"],
  ["yogurt", "🥛"],
  ["skyr", "🥛"],
  ["kefir", "🥛"],
  ["caffè", "☕"],
  ["caffe", "☕"],
  ["coffee", "☕"],
  ["espresso", "☕"],
  ["cappuccin", "☕"],
  ["tè ", "🍵"],
  ["tea", "🍵"],
  ["tisan", "🍵"],
  ["vino", "🍷"],
  ["wine", "🍷"],
  ["birr", "🍺"],
  ["beer", "🍺"],
  ["prosecc", "🥂"],
  ["spumant", "🥂"],
  ["champagne", "🥂"],
  ["smoothie", "🥤"],
  ["frullat", "🥤"],
  ["energy drink", "🥤"],
  ["spremut", "🧃"],

  // ─── Pane / cereali / pasta ───
  ["pane ", "🍞"],
  ["panin", "🥪"],
  ["bread", "🍞"],
  ["sandwich", "🥪"],
  ["tramezzin", "🥪"],
  ["toast", "🍞"],
  ["fette biscottat", "🍞"],
  ["cereal", "🥣"],
  ["muesli", "🥣"],
  ["granola", "🥣"],
  ["cornflakes", "🥣"],
  ["aven", "🌾"],
  ["oat", "🌾"],
  ["riso", "🍚"],
  ["rice", "🍚"],
  ["risotto", "🍚"],
  ["pasta", "🍝"],
  ["spaghett", "🍝"],
  ["penne", "🍝"],
  ["fusill", "🍝"],
  ["tagliatell", "🍝"],
  ["rigatoni", "🍝"],
  ["farfalle", "🍝"],
  ["orecchiett", "🍝"],
  ["paccheri", "🍝"],
  ["linguine", "🍝"],
  ["bucatini", "🍝"],
  ["lasagn", "🍝"],
  ["gnocch", "🍝"],
  ["farin", "🌾"],
  ["flour", "🌾"],
  ["pizz", "🍕"],
  ["focacc", "🍕"],
  ["baguette", "🥖"],
  ["piadin", "🥙"],
  ["wrap", "🥙"],
  ["tortill", "🌮"],
  ["cous cous", "🌾"],
  ["couscous", "🌾"],
  ["quinoa", "🌾"],
  ["farro", "🌾"],
  ["orzo", "🌾"],
  ["polent", "🌾"],

  // ─── Frutta ───
  ["mele", "🍎"],
  ["mela", "🍎"],
  ["banan", "🍌"],
  ["aranc", "🍊"],
  ["orange", "🍊"],
  ["mandarin", "🍊"],
  ["clementina", "🍊"],
  ["limon", "🍋"],
  ["lemon", "🍋"],
  ["lime", "🍋"],
  ["fragol", "🍓"],
  ["strawberr", "🍓"],
  ["pesch", "🍑"],
  ["peach", "🍑"],
  ["albicocc", "🍑"],
  ["apricot", "🍑"],
  ["uva", "🍇"],
  ["grape", "🍇"],
  ["cilieg", "🍒"],
  ["cherry", "🍒"],
  ["anguri", "🍉"],
  ["watermelon", "🍉"],
  ["melon", "🍈"],
  ["pere", "🍐"],
  ["pera", "🍐"],
  ["pear", "🍐"],
  ["ananas", "🍍"],
  ["pineapple", "🍍"],
  ["cocco", "🥥"],
  ["coconut", "🥥"],
  ["kiwi", "🥝"],
  ["avocado", "🥑"],
  ["mango", "🥭"],
  ["papaya", "🥭"],
  ["mirtill", "🫐"],
  ["blueberr", "🫐"],
  ["lamponi", "🫐"],
  ["lampon", "🫐"],
  ["ribes", "🫐"],
  ["more ", "🫐"],
  ["frutti di bosco", "🫐"],
  ["frutta secc", "🥜"],
  ["noc", "🥜"],
  ["walnut", "🥜"],
  ["mandorl", "🥜"],
  ["almond", "🥜"],
  ["hazelnut", "🥜"],
  ["arachid", "🥜"],
  ["peanut", "🥜"],
  ["pistacch", "🥜"],
  ["castagna", "🌰"],
  ["castagn", "🌰"],
  ["chestnut", "🌰"],
  ["datter", "🫐"],
  ["fichi", "🫐"],
  ["fico", "🫐"],
  ["melagrana", "🍎"],
  ["melograno", "🍎"],
  ["pomegranate", "🍎"],
  ["cachi", "🍊"],
  ["caco", "🍊"],

  // ─── Verdura ───
  ["pomodor", "🍅"],
  ["tomato", "🍅"],
  ["carot", "🥕"],
  ["carrot", "🥕"],
  ["patat", "🥔"],
  ["potato", "🥔"],
  ["insalat", "🥗"],
  ["lattug", "🥬"],
  ["spinac", "🥬"],
  ["spinach", "🥬"],
  ["broccol", "🥦"],
  ["cavolfiore", "🥦"],
  ["cauliflower", "🥦"],
  ["zucchin", "🥒"],
  ["cetriol", "🥒"],
  ["cucumber", "🥒"],
  ["peperon", "🫑"],
  ["pepper", "🫑"],
  ["cipoll", "🧅"],
  ["onion", "🧅"],
  ["aglio", "🧄"],
  ["garlic", "🧄"],
  ["mais", "🌽"],
  ["corn", "🌽"],
  ["fungh", "🍄"],
  ["mushroom", "🍄"],
  ["porcini", "🍄"],
  ["champignon", "🍄"],
  ["melanzan", "🍆"],
  ["eggplant", "🍆"],
  ["peperoncin", "🌶️"],
  ["chili", "🌶️"],
  ["zucca", "🎃"],
  ["radicchi", "🥬"],
  ["cicori", "🥬"],
  ["cavol", "🥬"],
  ["verz", "🥬"],
  ["carciofi", "🥬"],
  ["carciofo", "🥬"],
  ["finocchi", "🥬"],
  ["finocch", "🥬"],
  ["asparag", "🥬"],
  ["sedano", "🥬"],
  ["rucola", "🥬"],
  ["bieta", "🥬"],
  ["bietol", "🥬"],
  ["porr", "🧅"],
  ["scalogn", "🧅"],
  ["rapa", "🥕"],
  ["rape", "🥕"],
  ["barbabietol", "🥕"],
  ["ravanell", "🥕"],
  ["fagiolin", "🥒"],
  ["basilico", "🌿"],
  ["prezzemol", "🌿"],
  ["rosmarin", "🌿"],
  ["menta", "🌿"],
  ["salvia", "🌿"],
  ["origano", "🌿"],
  ["timo", "🌿"],
  ["erba cipoll", "🌿"],
  ["valeriana", "🥬"],
  ["songino", "🥬"],
  ["scarola", "🥬"],
  ["indivi", "🥬"],
  ["catalogna", "🥬"],
  ["friariell", "🥬"],
  ["cima di rapa", "🥬"],
  ["broccoletti", "🥦"],

  // ─── Proteine — carne ───
  ["pollo", "🍗"],
  ["chicken", "🍗"],
  ["tacchino", "🍗"],
  ["turkey", "🍗"],
  ["manzo", "🥩"],
  ["beef", "🥩"],
  ["vitello", "🥩"],
  ["maiale", "🥩"],
  ["pork", "🥩"],
  ["agnello", "🥩"],
  ["lamb", "🥩"],
  ["coniglio", "🥩"],
  ["bistecca", "🥩"],
  ["fettina", "🥩"],
  ["steak", "🥩"],
  ["scaloppin", "🥩"],
  ["arrosto", "🥩"],
  ["brasato", "🥩"],
  ["costolette", "🥩"],
  ["cotoletta", "🥩"],
  ["polpett", "🥩"],
  ["ragù", "🥩"],
  ["ragu", "🥩"],
  ["macinat", "🥩"],
  ["salsiccia", "🌭"],
  ["würstel", "🌭"],
  ["wurstel", "🌭"],
  ["hot dog", "🌭"],
  ["hamburger", "🍔"],
  ["burger", "🍔"],
  ["prosciutt", "🥓"],
  ["bacon", "🥓"],
  ["pancetta", "🥓"],
  ["salame", "🥓"],
  ["mortadell", "🥓"],
  ["bresaola", "🥓"],
  ["speck", "🥓"],
  ["coppa", "🥓"],
  ["guanciale", "🥓"],
  ["affettat", "🥓"],
  ["lonza", "🥓"],
  ["culatello", "🥓"],
  ["soppress", "🥓"],

  // ─── Proteine — pesce e frutti di mare ───
  ["tonno", "🐟"],
  ["tuna", "🐟"],
  ["salmone", "🐟"],
  ["salmon", "🐟"],
  ["pesce", "🐟"],
  ["fish", "🐟"],
  ["sgombro", "🐟"],
  ["mackerel", "🐟"],
  ["merluzzo", "🐟"],
  ["nasello", "🐟"],
  ["cod", "🐟"],
  ["orata", "🐟"],
  ["branzin", "🐟"],
  ["spigola", "🐟"],
  ["trota", "🐟"],
  ["acciugh", "🐟"],
  ["anchov", "🐟"],
  ["sardina", "🐟"],
  ["sardin", "🐟"],
  ["sogliola", "🐟"],
  ["platessa", "🐟"],
  ["pangasio", "🐟"],
  ["pesce spada", "🐟"],
  ["cernia", "🐟"],
  ["rana pescatrice", "🐟"],
  ["baccalà", "🐟"],
  ["stoccafisso", "🐟"],
  ["rombo", "🐟"],
  ["anguilla", "🐟"],
  ["halibut", "🐟"],
  ["dentice", "🐟"],
  ["ricciola", "🐟"],
  ["alice", "🐟"],
  ["alici", "🐟"],
  ["gamber", "🦐"],
  ["shrimp", "🦐"],
  ["prawn", "🦐"],
  ["scampi", "🦐"],
  ["calamari", "🦑"],
  ["calamar", "🦑"],
  ["totano", "🦑"],
  ["totani", "🦑"],
  ["polpo", "🐙"],
  ["polip", "🐙"],
  ["moscardini", "🐙"],
  ["seppi", "🦑"],
  ["cozz", "🦪"],
  ["vongol", "🦪"],
  ["ostrich", "🦪"],
  ["frutti di mare", "🦐"],

  // ─── Uova ───
  ["uova", "🥚"],
  ["uovo", "🥚"],
  ["egg", "🥚"],
  ["frittata", "🥚"],
  ["omelette", "🥚"],

  // ─── Tofu / proteine vegetali ───
  ["tofu", "🧈"],
  ["seitan", "🌾"],
  ["tempeh", "🌾"],
];

export function getFoodEmoji(category: string | null | undefined, name?: string | null): string {
  if (name) {
    const lower = name.toLowerCase().trim();
    // Simple: just scan all keywords, match if found as substring
    for (const [kw, emoji] of nameKeywords) {
      if (lower.includes(kw)) return emoji;
    }
  }

  if (category) {
    const key = category.toLowerCase().trim();
    if (categoryEmoji[key]) return categoryEmoji[key];
  }

  return "🛒";
}

export function getFoodImage(
  imageUrl: string | null | undefined,
  category: string | null | undefined,
  name?: string | null
): { type: "image" | "emoji"; value: string } {
  if (imageUrl) return { type: "image", value: imageUrl };
  return { type: "emoji", value: getFoodEmoji(category, name) };
}
