project_id = "dqhzopbjhxyhgcpedskl"

[functions.extract-expiry]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.analyze-food-photos]
verify_jwt = false

[functions.search-food]
verify_jwt = false

[functions.extract-diet-template]
verify_jwt = false

[functions.analyze-meal-photo]
verify_jwt = false
