
INSERT INTO public.ingredient_categories (ingredient_name, category, subcategory) VALUES
('insalata', 'verdure', NULL), ('zucchine', 'verdure', NULL), ('melanzane', 'verdure', NULL),
('peperoni', 'verdure', NULL), ('pomodoro', 'verdure', NULL), ('carote', 'verdure', NULL),
('cipolla', 'verdure', NULL), ('aglio', 'verdure', NULL), ('broccoli', 'verdure', NULL),
('cavolfiore', 'verdure', NULL), ('spinaci', 'verdure', NULL), ('funghi', 'verdure', NULL),
('zucca', 'verdure', NULL), ('sedano', 'verdure', NULL), ('patate', 'verdure', NULL),
('mela', 'frutta', NULL), ('banana', 'frutta', NULL), ('pera', 'frutta', NULL),
('arancia', 'frutta', NULL), ('limone', 'frutta', NULL), ('kiwi', 'frutta', NULL),
('fragole', 'frutta', NULL), ('uva', 'frutta', NULL), ('pesca', 'frutta', NULL),
('albicocca', 'frutta', NULL),
('farina 00', 'cereali_farine', NULL), ('farina 0', 'cereali_farine', NULL),
('farina integrale', 'cereali_farine', NULL), ('semola', 'cereali_farine', NULL),
('mais', 'cereali_farine', NULL), ('avena', 'cereali_farine', NULL),
('orzo', 'cereali_farine', NULL), ('cous cous', 'cereali_farine', NULL),
('pasta', 'pasta_riso_pane', NULL), ('pasta fresca', 'pasta_riso_pane', NULL),
('riso', 'pasta_riso_pane', NULL), ('pane bianco', 'pasta_riso_pane', NULL),
('pane integrale', 'pasta_riso_pane', NULL), ('fette biscottate', 'pasta_riso_pane', NULL),
('cracker', 'pasta_riso_pane', NULL), ('grissini', 'pasta_riso_pane', NULL),
('pangrattato', 'pasta_riso_pane', NULL),
('pollo', 'proteine_animali', NULL), ('tacchino', 'proteine_animali', NULL),
('manzo', 'proteine_animali', NULL), ('vitello', 'proteine_animali', NULL),
('maiale', 'proteine_animali', NULL), ('prosciutto crudo', 'proteine_animali', NULL),
('prosciutto cotto', 'proteine_animali', NULL), ('bresaola', 'proteine_animali', NULL),
('salsiccia', 'proteine_animali', NULL), ('tonno', 'proteine_animali', NULL),
('salmone', 'proteine_animali', NULL), ('merluzzo', 'proteine_animali', NULL),
('sgombro', 'proteine_animali', NULL), ('gamberi', 'proteine_animali', NULL),
('ceci', 'proteine_vegetali', NULL), ('lenticchie', 'proteine_vegetali', NULL),
('fagioli', 'proteine_vegetali', NULL), ('piselli', 'proteine_vegetali', NULL),
('fave', 'proteine_vegetali', NULL),
('latte', 'latticini', NULL), ('latte parzialmente scremato', 'latticini', NULL),
('yogurt', 'latticini', NULL), ('yogurt greco', 'latticini', NULL),
('mozzarella', 'latticini', NULL), ('ricotta', 'latticini', NULL),
('mascarpone', 'latticini', NULL), ('parmigiano', 'latticini', NULL),
('grana', 'latticini', NULL), ('pecorino', 'latticini', NULL),
('burro', 'latticini', NULL), ('panna', 'latticini', NULL),
('uova', 'uova', NULL),
('cioccolato', 'dolci_snack', NULL), ('barretta frutta secca', 'dolci_snack', 'frutta_secca'),
('zucchero', 'dolci_snack', NULL), ('miele', 'dolci_snack', NULL),
('biscotti', 'dolci_snack', NULL), ('merendine', 'dolci_snack', NULL),
('nutella', 'dolci_snack', NULL),
('noci', 'dolci_snack', 'frutta_secca'), ('mandorle', 'dolci_snack', 'frutta_secca'),
('nocciole', 'dolci_snack', 'frutta_secca'), ('pistacchi', 'dolci_snack', 'frutta_secca'),
('arachidi', 'dolci_snack', 'frutta_secca'),
('olio extravergine', 'condimenti', NULL), ('olio di semi', 'condimenti', NULL),
('aceto', 'condimenti', NULL), ('sale', 'condimenti', NULL),
('salsa di soia', 'condimenti', NULL), ('maionese', 'condimenti', NULL),
('ketchup', 'condimenti', NULL), ('senape', 'condimenti', NULL),
('pesto', 'condimenti', NULL)
ON CONFLICT (ingredient_name) DO NOTHING;

-- Compatibility matrix
INSERT INTO public.ingredient_compatibility_matrix (category_a, category_b, is_compatible) VALUES
('verdure', 'proteine_animali', true),
('verdure', 'proteine_vegetali', true),
('verdure', 'latticini', true),
('verdure', 'uova', true),
('verdure', 'pasta_riso_pane', true),
('verdure', 'cereali_farine', true),
('verdure', 'condimenti', true),
('verdure', 'dolci_snack', false),
('verdure', 'frutta', false),
('pasta_riso_pane', 'proteine_animali', true),
('pasta_riso_pane', 'proteine_vegetali', true),
('pasta_riso_pane', 'latticini', true),
('pasta_riso_pane', 'uova', true),
('pasta_riso_pane', 'condimenti', true),
('pasta_riso_pane', 'dolci_snack', false),
('cereali_farine', 'dolci_snack', true),
('cereali_farine', 'latticini', true),
('cereali_farine', 'uova', true),
('cereali_farine', 'frutta', true),
('frutta', 'latticini', true),
('frutta', 'dolci_snack', true),
('frutta', 'cereali_farine', true),
('proteine_animali', 'latticini', true),
('proteine_animali', 'uova', true),
('proteine_animali', 'condimenti', true),
('proteine_animali', 'dolci_snack', false),
('proteine_vegetali', 'latticini', true),
('proteine_vegetali', 'uova', true),
('proteine_vegetali', 'condimenti', true),
('latticini', 'uova', true),
('latticini', 'condimenti', true),
('latticini', 'dolci_snack', true),
('dolci_snack', 'uova', true),
('dolci_snack', 'condimenti', false)
ON CONFLICT (category_a, category_b) DO NOTHING;
