// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klczbpblgzuyylqogemz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsY3picGJsZ3p1eXlscW9nZW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzA1NTMsImV4cCI6MjA3MTY0NjU1M30.O1ZtkyQ76_2rfidFUzfjM5I7qBxTDilQwyOsz4atiDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});